apiVersion: v1
kind: Service
metadata:
  name: {{ include "gita-io-db.fullname" . }}
  namespace: {{ .Values.postgresql.namespace }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: {{ .Values.postgresql.port }}
      protocol: TCP
      name: postgres
  selector:
    app: {{ include "gita-io-db.name" . }}
